services:
  go-listener:
    build: ./go-listener
    ports:
      - "8080:8080"
    volumes:
      - ./go-listener/state.json:/app/state.json
    env_file:
      - .env
    environment:
      - AI_ANALYZER_URL=http://ai-analyzer:8000
      - DATABASE_URL=postgres://blocks:blocks@postgres:5432/blocks?sslmode=disable
    depends_on:
      ai-analyzer:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped

  ai-analyzer:
    build: ./analyzer
    ports:
      - "8000:8000"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=blocks
      - POSTGRES_PASSWORD=blocks
      - POSTGRES_DB=blocks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blocks -d blocks"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: